### ISSUE TITLE
RSS Feeds

### ISSUE THREAD

**Issue by matthias4217** [Cyxo/cyxo.github.io#1]
I'd be interested in a RSS feed for the blog articles. I suppose it shouldn't be too hard to setup one with Hugo. Thanks !

**Comment by Cyxo** [comment]
In fact the website already had an RSS feed configured by default, so I added a button in the top bar 😉

**Comment by matthias4217** [comment]
Thank you ! I was looking for a file named rss.xml or something along those lines, that's why I missed it the first time !
